const ADD_ITEM = 'ADD_ITEM';
const TOGGLE_ITEM = 'TOGGLE_ITEM';
const REMOVE_ITEM = 'REMOVE_ITEM';
const SEND_DATA = 'SEND_DATA';
const FETCH_DATA = 'FETCH_DATA';
const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
const REMOVE_LIST = 'REMOVE_LIST';
const FILTER_CARDS = 'FILTER_CARDS';
const SORT_CARDS = 'SORT_CARDS';
const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';

const SET_RENDERING_FILTER = 'SET_RENDERING_FILTER';

export const FilterOptions = {
	SHOW_ALL_ITEMS: 'SHOW_ALL_ITEMS',
	SHOW_COMPLETED_ITEMS: 'SHOW_COMPLETED_ITEMS',
  SHOW_ACTIVE_ITEMS: 'SHOW_ACTIVE_ITEMS',
  SHOW_IMPORTANT_ITEMS: 'SHOW_IMPORTANT_ITEMS',
};

export {
  ADD_ITEM,
  TOGGLE_ITEM,
  REMOVE_ITEM,
  SEND_DATA,
  FETCH_DATA,
  FETCH_DATA_REQUEST,
  FETCH_DATA_SUCCESS,
  FETCH_DATA_FAILURE,
  REMOVE_LIST,
  FILTER_CARDS,
  SORT_CARDS,
  SET_RENDERING_FILTER,
  FETCH_ITEM_SUCCESS
}